### ISSUE TITLE
Inconsistent date for class='new-date'" in blank.html.erb when item.updated > item.published.

### ISSUE THREAD

**Issue by jfg956** [planet-templates/planet-blank#1]
Hi,

when item.updated greater than item.published for the 1st item in a new-date, the date header will be inconsistent.  This is caused by the date header being populated with item.published while site.items.latest being sorted by item.updated.

An easy solution for fixing this in the scope of this template could be to replace item.published by item.updated with fixing item-footer for including both item.published and item.updated.  I might be able to submit a patch for this.

A larger scope solution, which would impact the Pluto software, could be to provide two versions of site.items.latest: latest_updated and latest_published, sorted respectively by item.updated and item.published.  The impact for this template would be to use latest_published instead of site.items.latest (latest_updated) for keeping using item.published as the date header.  I am not sure I can provide a patch of this scope.

Many thanks for looking into that.

Cheers, Jean-François Gagné

**Comment by geraldb** [comment]
Thanks for the detailed report on dates.  FYI: The blank template as the name implies, that is, blank - is a blank canvas - far from perfect and intented as a (minimal) starting point to change to your needs. 

Using ERB (Embedded RuBy) in the templates you can pretty much do whatever - incl. adding your own lastest_updated or such as needed.  

I'm not sure I understand your issue completely - dates in feeds are kind of a hard problem because in practice there are so many different ways and to top it off some feeds also "corrupt" the updated dates to push there own feed items or sometimes the wrong dates are just feed generation errors nobody cares and so on.

Anyways, if I  am misunderstanding something, please tell. Always happy to help out on the open street map setup. Thanks for using pluto. Cheers.   PS: for the feed item data  model about dates, see <https://github.com/feedreader/pluto/blob/master/pluto-models/lib/pluto/models/item.rb#L35>.

PS: Reading your issue again:

> A larger scope solution, which would impact the Pluto software, could be to provide two versions
> of site.items.latest: latest_updated and latest_published, sorted respectively by item.updated and
> item.published.

You can use your on latest_updated or latest_published "inline" use the latest SQL "order" code snipped from the link above:

      order( Arel.sql( "coalesce(items.updated,items.published,'1970-01-01') desc" )

and change to your needs and use instead of latest in the template.  Just remember you can do everything SQL can do because the data is stored in SQLite (sorry it's not MySQL in this case - but that is possible too).

**Comment by geraldb** [comment]
@jfg956  Just a little update - If you setup your own planet at <https://github.com/mysqlcommunity-org/planet>, for example.   I'm happy to help you out if you think there's something holding you back. Don't hesitate to open an issue / ticket at pluto itself if you're stuck @ <https://github.com/feedreader/pluto/issues>.  Cheers.

**Comment by jfg956** [comment]
@geraldb : you are right, I am trying to setup a Planet MySQL Community as a replacement for Planet MySQL, some motivations about this in (1).  For now, I am experimenting with Pluto to see if it fits my need, I will probably put the files I am using in (2) (or somewhere else if the name mysqlcommunity is causing problems with Oracle Trademark) when my experiments are more advanced.

(1): https://jfg-mysql.blogspot.com/2020/04/planning-for-after-planet-mysql-2.html

(2): https://github.com/mysqlcommunity-org/planet

Maybe the screenshots below will help you understand the issue.

![Capture1](https://user-images.githubusercontent.com/8471576/81324014-59721700-9064-11ea-8924-dedee8cb65de.PNG)

![Capture2](https://user-images.githubusercontent.com/8471576/81324026-5ecf6180-9064-11ea-8fd7-e85abfd1f800.PNG)

With the below patch, you get the below screenshot.

```
83c83
<   <%= item.published.strftime('%A, %d. %B %Y') %>
---
>   <%= item.updated.strftime('%A, %d. %B %Y') %>
139,140c139,142
<    <%= item.published.strftime('%H:%M') %> &bull;
<    <%= time_ago_in_words( item.published ) %>
---
>     Published <%= item.published.strftime('%A, %d. %B %Y %H:%M') %> &bull;
>               <%= time_ago_in_words( item.published ) %> &vert;
>     Updated <%= item.updated.strftime('%A, %d. %B %Y %H:%M') %> &bull;
>             <%= time_ago_in_words( item.updated ) %>
```

![Capture3](https://user-images.githubusercontent.com/8471576/81328064-46fadc00-906a-11ea-98de-4010bdedcd5c.PNG)

The feed generating this is (3).

(3):  https://jfg-mysql.blogspot.com/feeds/posts/default

**Comment by geraldb** [comment]
Thanks for the marking up the screenshoot. You are right I see now - that's a bug in the blank template - the recommendation is to always use the item.updated date (if the updated date is nil/null it will auto-default/fallback to published) in your templates.  TIP: To avoid any confusion I think I added a new item.date  earlier this year with the latest update (not yet reflected in this old templates here) that always uses updated before published.

If the the latest scope (just a "pre-built" SQL order clause) in line is still causing trouble:

     items = site.items.latest.limit(24)

try to "patch" it inline e.g. to your taste:

     items = site.items.order( Arel.sql( "coalesce(items.updated,items.published,'1970-01-01') desc" ).limit(24)

and I can also fix it in the pluto code to something more sane. But as far as I can tell I already changed it to give items.updated priority over items.published (see the SQL coalesce func).

**Comment by jfg956** [comment]
Link to pull request fixing this:
[Fix bug "Inconsistent [...] when item.updated > item.published.](https://github.com/planet-templates/planet-blank/pull/2)

**Comment by geraldb** [comment]
Again thanks for taking the time and sending in a patch. Keep it up.

If you setup your own planet and if you think there's something holding you back. Don't hesitate to open a (new) issue / ticket at pluto itself if you're stuck @ <https://github.com/feedreader/pluto/issues>.  Cheers.
